'use client';

import { useEffect, useState } from 'react';
import { ArrowRight, BarChart3, Check, FileSearch, MessageCircle, Scale, ShieldCheck, Target, WalletCards, Globe2 } from 'lucide-react';
import { LeadForm } from '@/components/lead-form';
import { PricingCard } from '@/components/pricing-card';
import { SamplePropertyReport } from '@/components/sample-property-report';
import { Toaster } from '@/components/ui/toaster';

const evidenceRows = [
  ['Property facts', 'What the listing supports', 'Verified'],
  ['Acquisition costs', 'Deposit, duty and financing', 'Calculated'],
  ['Market evidence', 'Comparable and market signals', 'Evidence-based'],
  ['Unknowns', 'What still needs confirmation', 'Clearly stated'],
];

export default function Home() {
  const [mounted, setMounted] = useState(false);
  useEffect(() => setMounted(true), []);

  return (
    <main className="min-h-screen overflow-x-hidden bg-[#F7F4EE] text-[#20231F]">
      <nav className="sticky top-0 z-50 border-b border-[#2A2D27]/10 bg-[#F7F4EE]/90 backdrop-blur-xl">
        <div className="mx-auto flex max-w-7xl items-center justify-between px-6 py-4 sm:px-10">
          <a href="#top" aria-label="EiXPropScore home" className="shrink-0"><img src="/images/eix-property-score-logo.svg" alt="EiXPropScore" className="h-12 w-auto object-contain sm:h-14" /></a>
          <div className="hidden items-center gap-8 md:flex"><a href="#how" className="text-sm font-medium text-[#3E413B] hover:text-[#20231F]">How it works</a><a href="/international-buyers" className="text-sm font-medium text-[#3E413B] hover:text-[#20231F]">International Buyers</a><a href="#report" className="text-sm font-medium text-[#3E413B] hover:text-[#20231F]">Example report</a><a href="#form" className="rounded-full bg-[#0E847B] px-5 py-2.5 text-sm font-semibold text-white hover:bg-[#08756D]">Score a Property</a></div>
          <span className="rounded-full bg-[#E8F7F5] px-3 py-1.5 text-xs font-semibold text-[#0E847B] ring-1 ring-[#0E847B]/15">Founding Beta</span>
        </div>
      </nav>

      <section id="top" className="relative overflow-hidden border-b border-[#2A2D27]/10 bg-[#F7F4EE]"><div className="absolute -right-40 -top-40 h-[520px] w-[520px] rounded-full bg-[#DDEFEA] blur-3xl" /><div className="absolute -left-48 bottom-[-220px] h-[520px] w-[520px] rounded-full bg-[#EEE5D6] blur-3xl" /><div className="relative mx-auto grid max-w-7xl items-center gap-14 px-6 py-16 sm:px-10 sm:py-24 lg:grid-cols-[1.02fr_.98fr] lg:py-28">
        <div className={mounted ? 'animate-fade-up' : 'opacity-0'}><span className="inline-flex rounded-full bg-white px-4 py-2 text-xs font-semibold text-[#0E847B] shadow-sm ring-1 ring-[#2A2D27]/10">South African Property Decision Intelligence</span><h1 className="mt-6 max-w-3xl text-4xl font-bold leading-[1.06] tracking-tight text-[#20231F] sm:text-5xl lg:text-[4.25rem]">Know the property before you make the decision.</h1><p className="mt-6 max-w-2xl text-base leading-8 text-[#3E413B] sm:text-lg">Paste a South African property listing or address. EiXPropScore™ turns available property facts, acquisition costs, market evidence and risk signals into one transparent decision report — without pretending to know what cannot be verified.</p><div className="mt-8 flex flex-wrap items-center gap-3"><a href="#form" className="group inline-flex items-center gap-2 rounded-xl bg-[#0E847B] px-6 py-4 text-sm font-semibold text-white shadow-[0_16px_40px_rgba(14,132,123,.18)] hover:bg-[#08756D]">Know Before You Buy — R149 <ArrowRight className="h-4 w-4" /></a><a href="/international-buyers" className="inline-flex items-center gap-2 rounded-xl border border-[#2A2D27]/10 bg-white px-6 py-4 text-sm font-semibold text-[#30332E] hover:bg-[#FCFAF6]"><Globe2 className="h-4 w-4 text-[#0E847B]" /> Buying from overseas?</a></div><div className="mt-8 flex flex-wrap gap-2 text-xs text-[#3E413B]">{['Property24', 'Private Property', 'Agency listings', 'Address search'].map((item) => <span key={item} className="rounded-full bg-white/80 px-3 py-1.5 ring-1 ring-[#2A2D27]/8">{item}</span>)}</div></div>
        <div className={mounted ? 'animate-scale-in' : 'opacity-0'}><div className="relative overflow-hidden rounded-[2rem] border border-[#2A2D27]/10 bg-[#FFFDF8] p-5 shadow-[0_28px_80px_rgba(42,45,39,.12)] sm:p-7"><div className="absolute inset-x-0 top-0 h-1 bg-[#0E847B]" /><div className="relative h-56 overflow-hidden rounded-[1.5rem] sm:h-64"><img src="/images/hero-property.jpg" alt="South African residential property" className="absolute inset-0 h-full w-full object-cover" /><div className="absolute inset-0 bg-gradient-to-t from-[#20231F]/45 via-transparent to-transparent" /><div className="absolute right-4 top-4 rounded-full bg-white/95 px-3 py-1.5 text-[10px] font-semibold text-[#0E847B] shadow-sm">Example property</div><div className="absolute bottom-4 left-4 rounded-xl bg-[#FFFDF8]/95 px-3 py-2 shadow-sm"><p className="text-[9px] font-semibold uppercase tracking-[.2em] text-[#0E847B]">Property evidence</p><p className="mt-0.5 text-xs font-semibold text-[#20231F]">Visual context, not valuation</p></div></div><div className="px-1 pb-1 pt-6"><div className="flex items-start justify-between gap-4"><div><p className="text-[10px] font-semibold uppercase tracking-[.22em] text-[#0E847B]">EiXPropScore™</p><h2 className="mt-2 text-2xl font-semibold tracking-tight">Evidence before opinion.</h2><p className="mt-2 text-sm text-[#3E413B]">A decision record, not a black-box answer.</p></div><div className="rounded-2xl bg-[#E8F7F5] px-4 py-3 text-center"><div className="text-3xl font-bold">72</div><div className="text-[10px] font-semibold uppercase tracking-wider text-[#0E847B]">/ 100</div></div></div><div className="mt-6 space-y-2.5">{evidenceRows.map(([title, desc, status]) => <div key={title} className="flex items-center justify-between rounded-xl border border-[#2A2D27]/8 bg-[#F8F5EF] px-4 py-3"><div><p className="text-sm font-medium">{title}</p><p className="mt-0.5 text-xs text-[#5F625B]">{desc}</p></div><span className="text-xs font-semibold text-[#0E847B]">{status}</span></div>)}</div><div className="mt-5 flex items-center gap-2 border-t border-[#2A2D27]/8 pt-4 text-xs text-[#3E413B]"><ShieldCheck className="h-4 w-4 text-[#0E847B]" /> When evidence isn't available, EiXPropScore™ tells you.</div></div></div></div>
      </div></section>

      <section className="border-b border-[#2A2D27]/8 bg-white/45"><div className="mx-auto grid max-w-7xl gap-6 px-6 py-8 sm:px-10 md:grid-cols-3">{[['R149', 'one property'], ['24 hrs', 'report delivery'], ['Evidence', 'before opinion']].map(([value, label]) => <div key={label} className="rounded-2xl bg-[#FFFDF8] p-5 ring-1 ring-[#2A2D27]/8"><div className="text-xl font-bold">{value}</div><div className="mt-1 text-sm text-[#3E413B]">{label}</div></div>)}</div></section>

      <section id="international" className="mx-auto max-w-7xl px-6 py-16 sm:px-10 sm:py-20"><div className="rounded-[2rem] border border-[#0E847B]/15 bg-[#E8F7F5] p-7 sm:p-10"><div className="grid gap-10 lg:grid-cols-[1fr_.8fr] lg:items-center"><div><span className="inline-flex items-center gap-2 rounded-full bg-white px-3 py-1.5 text-xs font-semibold text-[#0E847B]"><Globe2 className="h-3.5 w-3.5" /> New: International Buyer Intelligence</span><h2 className="mt-4 text-3xl font-bold tracking-tight sm:text-4xl">Buying South African property from overseas?</h2><p className="mt-4 max-w-2xl leading-7 text-[#3E413B]">Get the local property, market, lifestyle and risk intelligence you need before making a major decision from abroad. Built on the same evidence-first EiXPropScore™ engine.</p><a href="/international-buyers" className="mt-6 inline-flex items-center gap-2 rounded-xl bg-[#0E847B] px-5 py-3.5 text-sm font-semibold text-white hover:bg-[#08756D]">Explore International Buyer Intelligence <ArrowRight className="h-4 w-4" /></a></div><div className="grid gap-3"><div className="rounded-2xl bg-white p-4 ring-1 ring-[#2A2D27]/8"><p className="text-sm font-semibold">Holiday homes, retirement, relocation and investment</p><p className="mt-1 text-xs text-[#5F625B]">UK · Europe · USA · Middle East · worldwide</p></div><div className="rounded-2xl bg-white p-4 ring-1 ring-[#2A2D27]/8"><p className="text-sm font-semibold">Evidence before opinion</p><p className="mt-1 text-xs leading-5 text-[#5F625B]">Verified facts, assumptions, unknowns and due-diligence questions are separated clearly.</p></div></div></div></div></section>

      <section className="mx-auto max-w-7xl px-6 py-10 sm:px-10 sm:py-14"><div className="grid gap-5 md:grid-cols-3"><div className="group relative h-64 overflow-hidden rounded-[1.75rem] bg-[#DDD6C9]"><img src="/images/property-interior.jpg" alt="Premium property interior" className="h-full w-full object-cover" /><div className="absolute inset-0 bg-gradient-to-t from-[#20231F]/55 via-transparent to-transparent" /><p className="absolute bottom-5 left-5 text-sm font-semibold text-white">Inside the property</p></div><div className="group relative h-64 overflow-hidden rounded-[1.75rem] bg-[#DDD6C9]"><img src="/images/property-exterior.jpg" alt="South African property exterior" className="h-full w-full object-cover" /><div className="absolute inset-0 bg-gradient-to-t from-[#20231F]/55 via-transparent to-transparent" /><p className="absolute bottom-5 left-5 text-sm font-semibold text-white">Property context</p></div><div className="group relative h-64 overflow-hidden rounded-[1.75rem] bg-[#DDD6C9]"><img src="/images/cape-town-property.jpg" alt="Cape Town property context" className="h-full w-full object-cover" /><div className="absolute inset-0 bg-gradient-to-t from-[#20231F]/55 via-transparent to-transparent" /><p className="absolute bottom-5 left-5 text-sm font-semibold text-white">South African market context</p></div></div></section>

      <section id="report" className="mx-auto max-w-7xl px-6 py-20 sm:px-10 sm:py-28"><div className="grid items-center gap-12 lg:grid-cols-[.72fr_1.28fr]"><div><span className="text-xs font-semibold uppercase tracking-[.2em] text-[#0E847B]">See what you actually receive</span><h2 className="mt-3 text-3xl font-bold tracking-tight sm:text-4xl">Not just an AI answer. A property decision record.</h2><p className="mt-5 leading-7 text-[#3E413B]">Before paying R149, you should know exactly what the output looks like. The report is designed to show the reasoning behind the score — not hide it behind a number.</p><div className="mt-7 space-y-4">{[[Check,'Verified facts','What the listing or available evidence supports.'],[Scale,'Calculated scenarios','Acquisition costs, financing assumptions, yield and cash flow.'],[MessageCircle,'Risk flags','What could materially change the decision.'],[Target,'Actionable verdict','BUY, PROCEED WITH CAUTION, NEGOTIATE or WALK AWAY — with reasons.']].map(([Icon,title,desc]) => <div key={title as string} className="flex gap-3"><div className="mt-0.5 flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-[#E8F7F5] text-[#0E847B]"><Icon className="h-4 w-4" /></div><div><p className="text-sm font-semibold">{title as string}</p><p className="mt-1 text-sm leading-6 text-[#3E413B]">{desc as string}</p></div></div>)}</div></div><SamplePropertyReport /></div></section>

      <section id="how" className="border-y border-[#2A2D27]/8 bg-[#ECE7DC]/45"><div className="mx-auto max-w-7xl px-6 py-20 sm:px-10 sm:py-28"><div className="text-center"><span className="text-xs font-semibold uppercase tracking-[.2em] text-[#0E847B]">How it works</span><h2 className="mt-3 text-3xl font-bold tracking-tight sm:text-4xl">From property listing to decision</h2><p className="mx-auto mt-4 max-w-2xl leading-7 text-[#3E413B]">EiXPropScore™ does not ask you to trust a black-box score. It builds the score from the evidence available for the property.</p></div><div className="mt-12 grid gap-5 md:grid-cols-3">{[{icon:<FileSearch className="h-6 w-6"/>,title:'1. Give us the property',desc:'Paste a Property24, Private Property, agency or Facebook listing — or enter the address.'},{icon:<BarChart3 className="h-6 w-6"/>,title:'2. We analyse the evidence',desc:'EiXPropScore™ extracts facts, calculates acquisition scenarios and evaluates available market and risk evidence.'},{icon:<Target className="h-6 w-6"/>,title:'3. Make the decision',desc:'Receive the score, confidence level, financial picture, risks, unknowns and a clear next-step verdict.'}].map((step)=><div key={step.title} className="rounded-2xl bg-[#FFFDF8] p-7 ring-1 ring-[#2A2D27]/8"><div className="flex h-12 w-12 items-center justify-center rounded-xl bg-[#E8F7F5] text-[#0E847B]">{step.icon}</div><h3 className="mt-5 text-lg font-semibold">{step.title}</h3><p className="mt-2 text-sm leading-6 text-[#3E413B]">{step.desc}</p></div>)}</div></div></section>

      <section id="features" className="mx-auto max-w-7xl px-6 py-20 sm:px-10 sm:py-28"><div className="text-center"><span className="text-xs font-semibold uppercase tracking-[.2em] text-[#0E847B]">The EiXPropScore™ difference</span><h2 className="mt-3 text-3xl font-bold tracking-tight sm:text-4xl">What makes the score trustworthy</h2></div><div className="mt-12 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{[{icon:<BarChart3 className="h-5 w-5"/>,title:'Investment Score™',desc:'A transparent score built from the property facts and evidence available.'},{icon:<FileSearch className="h-5 w-5"/>,title:'Verified Property Facts',desc:'Uncertain or missing information is clearly identified instead of invented.'},{icon:<WalletCards className="h-5 w-5"/>,title:'Acquisition Intelligence',desc:'Deposit, transfer duty, financing assumptions and estimated acquisition cost.'},{icon:<ShieldCheck className="h-5 w-5"/>,title:'Transparent Risk Review',desc:'Red flags, unknowns and confidence indicators are surfaced before you decide.'}].map(({icon,title,desc})=><div key={title} className="rounded-2xl bg-[#FFFDF8] p-6 ring-1 ring-[#2A2D27]/8"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#E8F7F5] text-[#0E847B]">{icon}</div><h3 className="mt-5 font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-[#3E413B]">{desc}</p></div>)}</div></section>

      <section className="border-y border-[#2A2D27]/8 bg-[#F1ECE3]"><div className="mx-auto grid max-w-7xl gap-10 px-6 py-20 sm:px-10 sm:py-24 lg:grid-cols-[1fr_.7fr] lg:items-center"><div><span className="text-xs font-semibold uppercase tracking-[.2em] text-[#0E847B]">Why R149?</span><h2 className="mt-3 text-3xl font-bold tracking-tight sm:text-4xl">One property. One decision report.</h2><p className="mt-5 max-w-2xl leading-7 text-[#3E413B]">The Founding Beta is deliberately simple: submit one property, get one evidence-based decision report, and see exactly what the evidence supports — and what it does not.</p></div><PricingCard /></div></section>

      <section id="form" className="mx-auto max-w-7xl px-6 py-20 sm:px-10 sm:py-28"><div className="grid gap-12 lg:grid-cols-[.82fr_1.18fr] lg:items-start"><div><span className="text-xs font-semibold uppercase tracking-[.2em] text-[#0E847B]">Founding Beta</span><h2 className="mt-3 text-3xl font-bold tracking-tight sm:text-4xl">Know before you buy.</h2><p className="mt-5 leading-7 text-[#3E413B]">Submit the property you are considering. EiXPropScore™ will analyse the available evidence and deliver the report within 24 hours.</p><div className="mt-8 space-y-3 text-sm text-[#3E413B]"><div className="flex gap-3"><Check className="mt-0.5 h-4 w-4 shrink-0 text-[#0E847B]" />Property facts and listing evidence</div><div className="flex gap-3"><Check className="mt-0.5 h-4 w-4 shrink-0 text-[#0E847B]" />Acquisition and financial snapshot</div><div className="flex gap-3"><Check className="mt-0.5 h-4 w-4 shrink-0 text-[#0E847B]" />Market signals and investment analysis</div><div className="flex gap-3"><Check className="mt-0.5 h-4 w-4 shrink-0 text-[#0E847B]" />Risks, unknowns and due diligence checklist</div></div></div><LeadForm /></div></section>

      <section className="border-t border-[#2A2D27]/8 bg-[#ECE7DC]/35"><div className="mx-auto max-w-7xl px-6 py-8 sm:px-10"><p className="text-xs leading-6 text-[#4F524C]"><strong className="text-[#20231F]">Important:</strong> EiXPropScore™ is a decision-support tool, not a substitute for a professional property inspection, conveyancer, attorney, bank valuation, financial adviser or other professional due diligence. Scores and estimates depend on the evidence available and the assumptions used.</p></div></section>

      <footer className="border-t border-[#2A2D27]/8 bg-[#F7F4EE]"><div className="mx-auto flex max-w-7xl flex-col items-center justify-between gap-4 px-6 py-8 sm:px-10 sm:flex-row"><img src="/images/eix-property-score-logo.svg" alt="EiXPropScore" className="h-11 w-auto object-contain" /><p className="text-xs text-[#4F524C]">Evidence-based property decision intelligence for South Africa. © 2026 EntrprnriX Ai — EiXPropScore™. All rights reserved.</p></div></footer><Toaster />
    </main>
  );
}
